spring.application.name=trackmeh.foodtracking
# JWT Configuration
trackme.jwt-config.jwtSecret="2Owhi/PBpRSfz35LQMgP8RxpzfRbDVRpNQ/C9r+vhC8="
trackme.jwt-config.jwtExpirationMs=28800000

# variable
DB_HOST =${env:DB_HOST}
DB_USERNAME =${env:DB_USERNAME}
DB_PASSWORD =${env:DB_PASSWORD}
DB_SCHEMA =${env:DB_SCHEMA}

# database config
spring.datasource.url=${DB_HOST}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000


# jpa config
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.show-sql=true
spring.jpa.properties.hibernate.default_schema=${DB_SCHEMA}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE  


# spring.datasource.initialization-mode=always
# spring.datasource.initialize=true
# spring.datasource.schema=classpath:/schema.sql
# spring.datasource.continue-on-error=true