spring.application.name=trackmeh.foodtracking
# JWT Configuration
jwt.secret="testjwtsecretbymaniyah"
jwt.expiration=3600000

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5448/trackme_database
spring.datasource.username=trackme_user
spring.datasource.password=trackme
spring.jpa.properties.hibernate.default_schema=project


# spring.datasource.initialization-mode=always
# spring.datasource.initialize=true
# spring.datasource.schema=classpath:/schema.sql
# spring.datasource.continue-on-error=true