spring.application.name=trackmeh.foodtracking
# JWT Configuration
trackme.jwt-config.jwtSecret="2Owhi/PBpRSfz35LQMgP8RxpzfRbDVRpNQ/C9r+vhC8="
trackme.jwt-config.jwtExpirationMs=3600000

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5448/trackme_database
spring.datasource.username=trackme_user
spring.datasource.password=trackme
spring.jpa.properties.hibernate.default_schema=project
spring.jpa.hibernate.ddl-auto=update
# dialect สำหรับ PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# แสดง SQL บน console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# spring.datasource.initialization-mode=always
# spring.datasource.initialize=true
# spring.datasource.schema=classpath:/schema.sql
# spring.datasource.continue-on-error=true